# Generated by Django 4.2 on 2023-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tokens',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
