# Generated by Django 4.2 on 2023-05-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DalleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='dalle/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bot.telegramuser')),
            ],
        ),
    ]
