# Generated by Django 4.2 on 2023-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_file_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
