# Generated by Django 4.2 on 2023-05-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TelegramUser',
        ),
    ]
