# Generated by Django 4.2 on 2023-05-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotText',
        ),
    ]
